# Generated by Django 5.1.7 on 2025-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='用户邮箱')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('userRole', models.CharField(max_length=255, null=True, verbose_name='用户角色')),
                ('userAITime', models.CharField(max_length=255, verbose_name='最后登录时间')),
                ('isDelete', models.IntegerField(null=True, verbose_name='是否删除（0正常 1停用）')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
