# Generated by Django 5.1.7 on 2025-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sysuser_managers_sysuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='userAITime',
            field=models.CharField(max_length=255, verbose_name='积分'),
        ),
    ]
