# Generated by Django 5.1.7 on 2025-04-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_sysuser_points_sysuser_role_alter_sysuser_useraitime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='role',
            new_name='roleq',
        ),
    ]
