# Generated by Django 5.1.7 on 2025-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_role_sysuser_roleq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='roleq',
            new_name='role',
        ),
    ]
