# Generated by Django 5.1.7 on 2025-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='用户唯一标识')),
                ('session_key', models.CharField(max_length=128, verbose_name='会话密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小程序用户',
                'verbose_name_plural': '小程序用户',
            },
        ),
    ]
