# Generated by Django 5.1.7 on 2025-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_miniprogramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='openid',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='用户唯一标识'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='session_key',
            field=models.CharField(max_length=128, null=True, verbose_name='会话密钥'),
        ),
    ]
