# Generated by Django 5.1.8 on 2025-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sysuser_openid_sysuser_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='vip_points',
            field=models.PositiveIntegerField(default=0, verbose_name='VIP积分'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='普通积分'),
        ),
    ]
