# Generated by Django 5.1.7 on 2025-05-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_sysuser_vip_points_alter_sysuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(max_length=64, unique=True, verbose_name='分享码')),
                ('invite_count', models.PositiveIntegerField(default=0, verbose_name='邀请人数')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_info', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户分享',
                'verbose_name_plural': '用户分享',
            },
        ),
    ]
