# Generated by Django 5.1.7 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usershare'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershare',
            name='yaor',
            field=models.CharField(default='', max_length=100, verbose_name='邀请的用户'),
        ),
    ]
