# Generated by Django 5.1.7 on 2025-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_usershare_yaor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='openid',
            field=models.CharField(max_length=128, null=True, verbose_name='用户唯一标识'),
        ),
    ]
