# Generated by Django 5.1.8 on 2025-05-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_sysuser_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(help_text='正数表示增加，负数表示扣除', verbose_name='积分变动')),
                ('balance', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('transaction_type', models.CharField(help_text='例如：消费、奖励、退款等', max_length=50, verbose_name='交易类型')),
                ('reason', models.CharField(max_length=255, verbose_name='变动原因')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='详细说明')),
                ('related_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='相关任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
