# Generated by Django 5.1.7 on 2025-05-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_pointsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.SmallIntegerField(choices=[(0, '方式0'), (1, '方式1')], default=0, verbose_name='代理方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_relations', to=settings.AUTH_USER_MODEL, verbose_name='被代理账户')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_relations', to=settings.AUTH_USER_MODEL, verbose_name='代理用户')),
            ],
            options={
                'verbose_name': '用户代理关系',
                'verbose_name_plural': '用户代理关系',
                'unique_together': {('proxy', 'account')},
            },
        ),
    ]
