# Generated by Django 5.1.7 on 2025-05-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_records', to=settings.AUTH_USER_MODEL, verbose_name='被邀请用户')),
                ('user_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='user.usershare', verbose_name='分享记录')),
            ],
            options={
                'verbose_name': '被邀请用户记录',
                'verbose_name_plural': '被邀请用户记录',
                'unique_together': {('user_share', 'invited_user')},
            },
        ),
    ]
