# Generated by Django 5.1.7 on 2025-04-28 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='realtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '真标签',
                'verbose_name_plural': '真标签',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='标签描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('text', models.TextField(verbose_name='文字')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('image_path_res', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片路径')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('english_prompt', models.TextField(blank=True, null=True, verbose_name='英文提示词')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('generation_method', models.CharField(max_length=100, verbose_name='生成方法')),
                ('realtag', models.ManyToManyField(to='template.realtag', verbose_name='真标签')),
                ('tag', models.ManyToManyField(to='template.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '范例',
                'verbose_name_plural': '范例',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('mask', models.CharField(blank=True, max_length=255, null=True, verbose_name='遮罩')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('realtag', models.ManyToManyField(to='template.realtag', verbose_name='真标签')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '模版',
                'verbose_name_plural': '模版',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template', verbose_name='模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template', verbose_name='模版')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
                'unique_together': {('user', 'template')},
            },
        ),
    ]
