# Generated by Django 5.1.7 on 2025-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='文字'),
        ),
    ]
