# Generated by Django 5.1.7 on 2025-05-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_template_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
