# Generated by Django 5.1.7 on 2025-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_remove_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='fromuser',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
