# Generated by Django 5.1.7 on 2025-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_realtag_is_deleted_tag_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='fromuser',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
