# Generated by Django 5.1.7 on 2025-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_example_fromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtag',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='默认是给模板用的'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_temp',
            field=models.BooleanField(default=False, verbose_name='默认是范例分类'),
        ),
    ]
