# Generated by Django 5.1.7 on 2025-05-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_realtag_is_example_tag_is_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.tag', verbose_name='标签'),
        ),
    ]
