# Generated by Django 5.1.7 on 2025-05-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_realtag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtag',
            name='is_one',
            field=models.BooleanField(default=False, verbose_name='一级分类'),
        ),
    ]
