# Generated by Django 5.1.7 on 2025-05-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_realtag_is_one'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.CreateModel(
            name='ExampleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.example', verbose_name='范例')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户点赞范例',
                'verbose_name_plural': '用户点赞范例',
                'unique_together': {('user', 'example')},
            },
        ),
    ]
