# Generated by Django 5.1.7 on 2025-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_example_like_count_examplelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='标题'),
        ),
    ]
