version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mojie0303
      MYSQL_DATABASE: MJApplicationDate
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
  mysql-data: