# Generated by Django 5.1.7 on 2025-04-06 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('seed', models.IntegerField(verbose_name='种子值')),
                ('description', models.CharField(max_length=255, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='订单总金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实付金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='优惠金额')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已发货'), (3, '已完成'), (4, '已取消'), (5, '已退款')], default=0, verbose_name='订单状态')),
                ('payment_method', models.IntegerField(blank=True, choices=[(1, '支付宝'), (2, '微信支付'), (3, '银行卡'), (4, '现金')], null=True, verbose_name='支付方式')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('receiver_address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('receiver_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮政编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='订单备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product', verbose_name='商品信息')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='支付ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支付金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币类型')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '支付失败'), (3, '已退款'), (4, '已取消')], default=0, verbose_name='支付状态')),
                ('payment_method', models.IntegerField(choices=[(1, '支付宝'), (2, '微信支付'), (3, '银行卡')], verbose_name='支付方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易流水号')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应数据')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='支付描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='支付用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='退款ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='退款金额')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='退款原因')),
                ('status', models.IntegerField(choices=[(0, '处理中'), (1, '成功'), (2, '失败')], default=0, verbose_name='退款状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('refund_time', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='退款流水号')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应数据')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='order.payment', verbose_name='关联支付')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'db_table': 'refund',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_order_i_f08ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_1c1ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payment_user_id_aa0b64_idx'),
        ),
    ]
