# Generated by Django 5.1.7 on 2025-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seed',
            new_name='points',
        ),
    ]
