# Generated by Django 5.2 on 2025-04-08 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_product_gift_points_product_is_delete_product_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('vip_basic', '基础VIP'), ('vip_premium', '高级VIP'), ('vip_platinum', '白金VIP')], default='vip_basic', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP会员信息',
                'verbose_name_plural': 'VIP会员信息',
                'indexes': [models.Index(fields=['end_time', 'is_active'], name='order_userv_end_tim_c7f856_idx')],
            },
        ),
    ]
