# Generated by Django 5.1.8 on 2025-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_uservip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exchange_min_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='最小兑换金额'),
        ),
    ]
