# Generated by Django 5.1.7 on 2025-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_product_exchange_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='way',
            field=models.IntegerField(default=0, verbose_name='平台'),
        ),
    ]
