# Generated by Django 5.1.8 on 2025-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_product_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservip',
            name='level',
            field=models.CharField(choices=[('vip_basic', '月度VIP'), ('vip_premium', '季度VIP'), ('vip_platinum', '年度VIP')], default='vip_basic', max_length=20),
        ),
    ]
