# Generated by Django 5.2 on 2025-04-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='templateVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('video_address', models.CharField(max_length=255, verbose_name='模板视频的地址')),
                ('description', models.TextField(verbose_name='描述')),
                ('video_method', models.CharField(max_length=100, null=True, verbose_name='视频类别')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('isDelete', models.IntegerField(null=True, verbose_name='是否删除（0正常 1停用）')),
                ('userVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '视频生成记录',
                'verbose_name_plural': '视频生成记录',
                'db_table': 'template_video',
            },
        ),
    ]
