# Generated by Django 5.1.7 on 2025-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateVideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevideo',
            name='audeo_address',
            field=models.CharField(max_length=255, null=True, verbose_name='模板音频的地址'),
        ),
        migrations.AddField(
            model_name='templatevideo',
            name='status',
            field=models.IntegerField(null=True, verbose_name='状态（0正常 1停用）'),
        ),
    ]
