# Generated by Django 5.1.7 on 2025-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateVideo', '0002_templatevideo_audeo_address_templatevideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevideo',
            name='task_id',
            field=models.CharField(max_length=255, null=True, verbose_name='模板音频的地址'),
        ),
    ]
