# Generated by Django 5.1.8 on 2025-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0004_imageuploadrecord_comfyui_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='任务类型代码')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('handler_name', models.CharField(help_text="处理方法名称或'generic'表示使用通用处理器", max_length=100, verbose_name='处理器名称')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='配置')),
                ('priority_order', models.IntegerField(default=0, verbose_name='排序优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务类型',
                'verbose_name_plural': '任务类型',
                'ordering': ['priority_order', 'name'],
            },
        ),
    ]
