# Generated by Django 5.1.8 on 2025-05-14 14:14

from django.db import migrations


def add_initial_task_types(apps, schema_editor):
    """
    添加初始任务类型数据
    """
    TaskType = apps.get_model('templateImage', 'TaskType')
    
    # 定义初始任务类型
    task_types = [
        {
            'name': 'text_to_image',
            'display_name': '文生图',
            'description': '基于文本提示生成图像',
            'is_active': True,
            'handler_name': '_process_text_to_image_task',
            'priority_order': 10,
        },
        {
            'name': 'image_to_image',
            'display_name': '图生图',
            'description': '基于输入图像生成新图像',
            'is_active': True,
            'handler_name': '_process_image_to_image_task',
            'priority_order': 20,
        },
        {
            'name': 'photo_expansion',
            'display_name': '图片扩展',
            'description': '扩展现有图片的尺寸或内容',
            'is_active': True,
            'handler_name': '_process_photo_expansion_task',
            'priority_order': 30,
        },
        {
            'name': 'tti_api',
            'display_name': 'API文生图',
            'description': 'API直传的文生图任务',
            'is_active': True,
            'handler_name': '_process_tti_api_task',
            'priority_order': 40,
        },
        {
            'name': 'iti_api',
            'display_name': 'API图生图',
            'description': 'API直传的图生图任务',
            'is_active': True,
            'handler_name': '_process_iti_api_task',
            'priority_order': 50,
        },
        {
            'name': 'product_replace',
            'display_name': '产品替换',
            'description': '替换图片中的产品',
            'is_active': True,
            'handler_name': '_process_product_replace_task',
            'priority_order': 60,
        },
        {
            'name': 'product_clue',
            'display_name': '产品线索',
            'description': '产品线索任务',
            'is_active': True,
            'handler_name': '_process_product_clue_task',
            'priority_order': 70,
        },
        {
            'name': 'clue_product',
            'display_name': '线索产品',
            'description': '线索产品任务',
            'is_active': True,
            'handler_name': '_process_clue_product_task',
            'priority_order': 80,
        },
        {
            'name': 'white_background',
            'display_name': '白底图',
            'description': '白底图任务',
            'is_active': True,
            'handler_name': '_process_white_background_task',
            'priority_order': 90,
        },
        {
            'name': 'fine_detail',
            'display_name': '细节精修',
            'description': '细节精修任务',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 100,
        },
        {
            'name': 'multi_image_to_image',
            'display_name': '多图生图',
            'description': '基于多张输入图像生成新图像',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 110,
        },
        {
            'name': 'wide_picture',
            'display_name': '扩图',
            'description': '扩展图像尺寸的任务',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 120,
        },
        {
            'name': 'internal_supplementation',
            'display_name': '内补',
            'description': '图像内容填充任务',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 130,
        },
        {
            'name': 'internal_supplementation_and_removal',
            'display_name': '内补去除',
            'description': '图像内容填充和去除任务',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 140,
        },
        {
            'name': 'complete_redrawing',
            'display_name': '重绘精修',
            'description': '完全重绘和精修图像',
            'is_active': True,
            'handler_name': 'generic',
            'priority_order': 150,
        },
    ]
    
    # 批量创建任务类型
    for task_type in task_types:
        TaskType.objects.create(**task_type)


def remove_task_types(apps, schema_editor):
    """
    移除所有任务类型数据
    """
    TaskType = apps.get_model('templateImage', 'TaskType')
    TaskType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0005_tasktype'),
    ]

    operations = [
        migrations.RunPython(add_initial_task_types, remove_task_types),
    ]
