# Generated by Django 5.1.8 on 2025-05-06 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCloudImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, verbose_name='图片名称')),
                ('image_url', models.TextField(verbose_name='图片URL')),
                ('image_size', models.PositiveIntegerField(verbose_name='图片大小(字节)')),
                ('image_type', models.CharField(default='image/png', max_length=20, verbose_name='图片类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('source', models.CharField(default='comfyui', max_length=50, verbose_name='图片来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户云空间图片',
                'verbose_name_plural': '用户云空间图片',
                'db_table': 'user_cloud_image_storage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_cloud__user_id_83bb08_idx'), models.Index(fields=['created_at'], name='user_cloud__created_8c0b14_idx'), models.Index(fields=['is_deleted'], name='user_cloud__is_dele_953790_idx')],
            },
        ),
    ]
