# Generated by Django 5.1.8 on 2025-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0002_usercloudimagestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfyuitask',
            name='auto_save_to_cloud',
            field=models.BooleanField(default=False, verbose_name='自动保存到云空间'),
        ),
        migrations.AddField(
            model_name='comfyuitask',
            name='saved_to_cloud',
            field=models.BooleanField(default=False, verbose_name='是否已保存到云空间'),
        ),
    ]
