# Generated by Django 5.1.8 on 2025-05-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0003_comfyuitask_auto_save_to_cloud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadrecord',
            name='comfyUI_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templateImage.comfyuitask', verbose_name='对应的任务信息'),
        ),
    ]
