# Generated by Django 5.1.8 on 2025-06-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateImage', '0006_add_initial_task_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsDeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_time', models.DateTimeField(auto_now_add=True, verbose_name='扣除时间')),
                ('points_deducted', models.IntegerField(verbose_name='扣除积分数量')),
                ('deduction_type', models.CharField(choices=[('VIP', 'VIP积分'), ('REGULAR', '普通积分')], max_length=20, verbose_name='扣除积分类型')),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='任务ID')),
                ('image_upload_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templateImage.imageuploadrecord', verbose_name='图片上传记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分扣除历史',
                'verbose_name_plural': '积分扣除历史',
                'db_table': 'points_deduction_history',
                'ordering': ['-deduction_time'],
            },
        ),
    ]
